context:
  version: "1.94.0"

package:
  name: exoscale-cli
  version: ${{ version }}

source:
  url: https://github.com/exoscale/cli/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a150b6a70ab4242f0b556020f0e8a8a96eed5957a46bd9ebb8b753153e012715
  target_directory: src

build:
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses
    - if: unix
      then: go build -v -o $PREFIX/bin/exo -ldflags="-s -w -X main.GitVersion=${{ version }}"
      else: go build -v -o %LIBRARY_BIN%\exo.exe -ldflags="-s -X main.GitVersion=${{ version }}"

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script: exo version
  - package_contents:
      bin:
        - exo
      strict: true

about:
  homepage: https://github.com/exoscale/cli
  summary: Command-line tool for everything at Exoscale
  description: |
    Manage your Exoscale infrastructure easily from the command-line.
    Provides access to compute, storage, DNS, and other Exoscale services
    via the exo command.
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  documentation: https://community.exoscale.com/documentation/tools/exoscale-command-line-interface/
  repository: https://github.com/exoscale/cli

extra:
  recipe-maintainers:
    - ytausch
